---@class Sides This "API" provides a global table to allow you to refer to sides / directions by name, as opposed to their numbers. The underlying number values are identical to Minecraft's internal numbering (as well as the `ForgeDirection` Enum). This table serves as a two-directional look-up, so you can resolve names to numbers, but also numbers back to a human readable name. For example, `sides.top` has the value `1`, whereas `sides[1]` has the string value `top`. A couple of aliases for the side names are available, so it's less likely to accidentally pick the wrong one. These are the basic values:
---@field public bottom number Number:0
---@field public down number Number:0
---@field public negy number Number:0
---@field public top number Number:1
---@field public up number Number:1
---@field public posy number Number:1
---@field public back number Number:2
---@field public north number Number:2
---@field public negz number Number:2
---@field public front number Number:3
---@field public south number Number:3
---@field public posz number Number:3
---@field public forward number Number:3
---@field public right number Number:4
---@field public west number Number:4
---@field public negx number Number:4
---@field public left number Number:5
---@field public east number Number:5
---@field public posx number Number:5
---@field __index fun(side:number):string Converts numbers back to strings
local sides = require("sides")